# 樸素貝式分類器 (Naive Bayes classifier)

In [1]:
library(MASS)
library(klaR)

# Iris 資料集

In [2]:
data(iris)
index <- c(sample(1:50,35), sample(51:100,35), sample(101:150,35))
training <- iris[index,]
testing <- iris[-index,]

fit_bayes <- NaiveBayes(Species ~ ., data=training)
pre_bayes <- predict(fit_bayes, testing)
table(testing$Species, pre_bayes$class)
cat("\n  Accuracy:",
    sum(as.numeric(pre_bayes$class == testing$Species)) / nrow(testing)*100,"%")

            
             setosa versicolor virginica
  setosa         15          0         0
  versicolor      0         14         1
  virginica       0          1        14


  Accuracy: 95.55556 %

In [3]:
# fit的結果
fit_bayes$apriori

# tables of mean and standard deviation (in that order)
print(fit_bayes$tables)

grouping
    setosa versicolor  virginica 
 0.3333333  0.3333333  0.3333333 

$Sepal.Length
               [,1]      [,2]
setosa     4.960000 0.3541352
versicolor 5.951429 0.5332318
virginica  6.645714 0.7101544

$Sepal.Width
               [,1]      [,2]
setosa     3.397143 0.3996217
versicolor 2.785714 0.2942017
virginica  2.997143 0.3285312

$Petal.Length
               [,1]      [,2]
setosa     1.448571 0.1884479
versicolor 4.300000 0.4721665
virginica  5.637143 0.5906555

$Petal.Width
               [,1]      [,2]
setosa     0.240000 0.1034692
versicolor 1.340000 0.1928120
virginica  2.031429 0.2665371



In [4]:
# 寫成函式
fit_NaiveBayes <- function(rawdata) {
    # print(rawdata[index,class])
    last <- ncol(rawdata)
    index <- sample(1:nrow(rawdata), round(nrow(rawdata)*0.7))
    
    fit_bayes <- NaiveBayes(rawdata[index,last] ~ ., data=rawdata[index,-last])
    pre_bayes <- predict(fit_bayes, rawdata[-index,-last])
    print(table(rawdata[-index,last], pre_bayes$class))
    cat("\n  Accuracy:",
        sum(as.numeric(pre_bayes$class == rawdata[-index,last])) / nrow(rawdata[-index,])*100,"%\n\n")
    return(fit_bayes)
    }

# 性別資料集

In [5]:
gender_size <- read.csv("../data_files/gender_size.csv", stringsAsFactors = TRUE)
fit_bayes <- fit_NaiveBayes(gender_size)

        
         female male
  female     18    1
  male        0   23

  Accuracy: 97.61905 %



In [6]:
# 預測資料(1 -> female, 2 -> male)
x1 <- data.frame(Height= 175, Weight=72, Waist=32)
x2 <- data.frame(Height= 165, Weight=58, Waist=28)
cat('\nx1:', predict(fit_bayes, x1)$class)
cat('\nx2:', predict(fit_bayes, x2)$class)


x1: 2
x2: 1

# 鐵達尼號資料集

In [7]:
titanic_data <-read.csv("../data_files/titanic.csv", header=T, sep=",",stringsAsFactors = TRUE)

# 整理數據
titanic <- na.exclude(titanic_data) #remove missing values
rw <- c(which(titanic$age==9999), which(titanic$fare==9999))  
#identify the id which has missing values in age or fare
titan <- titanic[-rw, 2:5]
titan$survival <- titanic[-rw, 10] #set survival

titan[which(titan[,1]==0), 1]<-"male"  #rename 0 by male
titan[which(titan[,1]==1), 1]<-"female"  #rename 1 by female
titan[,1] <- as.factor(titan$gender)

titan[which(titan[,5]==1), 5]<-"yes"
titan[which(titan[,5]==0), 5]<-"no"
titan[,5]<-as.factor(titan[,"survival"])

fit_bayes <-fit_NaiveBayes(titan)

     
       no yes
  no  223  14
  yes  77  72

  Accuracy: 76.42487 %

